### ISSUE TITLE
Dotfiles cause several Issues

### ISSUE THREAD

**Issue by KaptainAhoibrause** [ylpoonlg/dots#1]
Hey there,

I'm trying out qtile and I love your setup you posted on r/unixporn! I wanted to use it as a base for starting in qtile and first changing some simplethings like colors. But when I "installed" your dotfiles, some weird things started to happen.

1. Some Hotkeys you defined seem to stop working, f.e. I can't open rofi, only via Terminal.
2. There are some strange Issues when having multiple Apps open, I posted a Screenshot for this.
3. The EWW Bar doesn't show up.
4. I can't visually close the last window, it's still there, but I can't interact wth it.

I have installed all dependencies of qtile. Also, there is eww via aur and picom via pacman.

Is there maybe some Application missing?

Thank you!

**Comment by ylpoonlg** [comment]
Hi,

It has been a while since I last updated this repo. I have just pushed my up-to-date configs, see if that helps. I am not aware of any major breaking changes though.

1. Make sure you have put the launch scripts, e.g. `~/.config/rofi/scripts`. You may have to edit the scripts to make them work on your machine.
2. Sorry I can't see the screenshot
3. Check `~/.config/qtile/scripts/load-bar.sh`, change the EWW variable to the path of your eww executable
4. I remember having this issue myself before, but I forgot what the cause was and how I fixed it :(

It would also be helpful to look at the log file when trying to diagnose the issues.
And I don't think you need anything else to use the setup.

Hope that answers your questions.

**Comment by KaptainAhoibrause** [comment]
Hey,

thank you, I didn't expect getting an answer that quickly!

I just reinstalled everything (qtile, picom, dunst, eww) and their dependencies. Then, I copied all config files from you updated config. Now, if I try to enter QTile via SDDM, the screen doesn't update, but I get notifications, which stay in the corner for ever.

`qtile check` gives me no errors in the config file, only some errors in file under `/tmp` which defenitely not exist. The only thing I can try is to go through every script and config to get it to work on my machine, but this could take some time, so maybe I can answer in a few days earliest.

Thank you so much!!

**Comment by KaptainAhoibrause** [comment]
![Uploading Bildschirmfoto_20240824_130938.png…]()

**Comment by KaptainAhoibrause** [comment]
OK, it still doesn't work, but can you explain where you start the scripts in `~/.config/qtile/scripts`? I can't find the place where they are executed.

**Comment by ylpoonlg** [comment]
The scripts are referenced and defined as path variables in `settings.py`, then called by lazy.spawn() in `keymaps.py`

**Comment by KaptainAhoibrause** [comment]
Yay, I finally changed the right things so qtile starts now!!

I still have to change some things, for example the eww and picom config and when I click on widgets in the bar, they don't open. Thank you so much for your help!
